"""Format a Gauntlet JSON report into a Markdown PR comment.

    python format_comment.py <report.json> <fail-on>  > comment.md
"""

import json
import sys

MARKER = "<!-- gauntlet-report -->"
EMOJI = {"CRITICAL": "🟥", "HIGH": "🟧", "MEDIUM": "🟨", "LOW": "🟦", "INFO": "⬜"}


def main():
    path = sys.argv[1]
    fail_on = sys.argv[2] if len(sys.argv) > 2 else "HIGH"
    try:
        with open(path) as fh:
            report = json.load(fh)
    except (OSError, json.JSONDecodeError):
        print(f"{MARKER}\n### 🛡️ Gauntlet\nNo report produced (the run errored before writing one).")
        return

    s = report.get("summary", {})
    by_sev = s.get("by_severity", {})
    failed = s.get("probes_failed", 0)
    total = s.get("probes_run", 0)
    findings = s.get("findings_total", 0)
    clean = findings == 0

    lines = [MARKER, "### 🛡️ Gauntlet — adversarial agent report", ""]
    if clean:
        lines.append(f"✅ **Clean run.** {total} probes fired, no findings against your canaries.")
    else:
        order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
        chips = "  ".join(f"{EMOJI[k]} {k} **{by_sev[k]}**" for k in order if k in by_sev)
        lines.append(f"**{failed}/{total}** probes failed · **{findings}** findings · gate `{fail_on}`")
        lines.append("")
        lines.append(chips)

    worst = report.get("worst_failures", [])
    if worst:
        lines += ["", "<details><summary>Worst failures</summary>", ""]
        for f in worst[:5]:
            lines.append(f"**{EMOJI.get(f['severity'],'')} {f['severity']}** · `{f['category']} / {f['probe_id']}`")
            probe = (f.get("probe") or "").replace("\n", " ")[:160]
            resp = (f.get("agent_response") or "").replace("\n", " ")[:160]
            lines.append(f"- probe: `{probe}`")
            lines.append(f"- response: `{resp or '<empty>'}`")
            for fl in f.get("findings", []):
                lines.append(f"  - {fl['severity']}: {fl['detail']}")
            lines.append("")
        lines.append("</details>")

    lines += ["", "<sub>Generated by [Gauntlet](https://github.com/GauntletVectorLabs/gauntlet) — break your agent before your users do.</sub>"]
    print("\n".join(lines))


if __name__ == "__main__":
    main()
